module.exports = {
  animals: [
    // Added hard coded dogs id: 62644447 - 62533328
    {
      id: 62644447,
      organization_id: "CA1612",
      url: "https://www.oregonhumane.org/adopt/details/281449/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Red Heeler",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: { primary: "White / Red", secondary: null, tertiary: null },
      age: "7 Months",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Lamont",
      description: null,
      organization_animal_id: "LACA-A-8411",
      photos: [
        {
          full: "../client/src/assets/images/Lamont.jpeg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:14+0000",
      published_at: "2023-04-14T17:55:13+0000",
      distance: null,
      contact: {
        email: "adoptions@spcala.com",
        phone: "(310) 676-1149",
        address: {
          address1: "12910 Yukon Ave.",
          address2: null,
          city: "Hawthorne",
          state: "CA",
          postcode: "90250",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644447" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ca1612" },
      },
    },
    {
      id: 62644448,
      organization_id: "CA1612",
      url: "https://www.oregonhumane.org/adopt/details/282975/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "German Shepherd, Australian Cattledog",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: "Merle",
        secondary: null,
        tertiary: null,
      },
      age: "1 year and 4 months",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Taki",
      description: null,
      organization_animal_id: "LACA-A-8444",
      photos: [
        {
          full: "../client/src/assets/images/Taki.jpeg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:14+0000",
      published_at: "2023-04-14T17:55:13+0000",
      distance: null,
      contact: {
        email: "adoptions@spcala.com",
        phone: "(310) 676-1149",
        address: {
          address1: "12910 Yukon Ave.",
          address2: null,
          city: "Hawthorne",
          state: "CA",
          postcode: "90250",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644448" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ca1612" },
      },
    },
    {
      id: 62644446,
      organization_id: "AR372",
      url: "https://www.oregonhumane.org/adopt/details/284439/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "American Pit Bull",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "	White / Tan",
        secondary: null,
        tertiary: null,
      },
      age: "11 Months",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: ["Heartworm Positive", "Microchipped"],
      name: "Preston Wiggleston ",
      description: null,
      organization_animal_id: "KKFS-A-8070",
      photos: [
        {
          full: "../client/src/assets/images/PrestonWiggleston.jpg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:13+0000",
      published_at: "2023-04-14T17:55:12+0000",
      distance: null,
      contact: {
        email: "fortsmithanimalhaven@gmail.com",
        phone: "(479) 551-2221",
        address: {
          address1: "4800 South 46th Street",
          address2: null,
          city: "Fort Smith",
          state: "AR",
          postcode: "72903",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644446" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ar372" },
      },
    },
    {
      id: 62644444,
      organization_id: "FL279",
      url: "https://www.oregonhumane.org/adopt/details/276703/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "German Shepherd",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "White / Sable",
        secondary: null,
        tertiary: null,
      },
      age: "3 years and 6 months",
      gender: "Female",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Ginger",
      description: null,
      organization_animal_id: "PAAR-A-1538",
      photos: [
        {
          full:"../client/src/assets/images/Ginger.jpeg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:12+0000",
      published_at: "2023-04-14T17:55:11+0000",
      distance: null,
      contact: {
        email: "adoptions@peggyadams.org",
        phone: "(561) 686-3663",
        address: {
          address1: "3100 North Military Trail",
          address2: null,
          city: "West Palm Beach",
          state: "FL",
          postcode: "33409",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644444" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/fl279" },
      },
    },
    {
      id: 62644445,
      organization_id: "OK57",
      url: "https://www.oregonhumane.org/adopt/details/275675/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Labrador, Mix",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Yellow / White",
        secondary: null,
        tertiary: null,
      },
      age: "2 years and 2 months ",
      gender: "Male",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Gunther",
      description:
        "Want to get more exercise? Action is my middle name. My \u0026amp;#34;Let\u0026amp;#39;s GO!\u0026amp;#34; lifestyle will keep you motivated to get...",
      organization_animal_id: "TUL-A-4698",
      photos: [
        {
          full: "../client/src/assets/images/Gunther.jpeg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:12+0000",
      published_at: "2023-04-14T17:55:11+0000",
      distance: null,
      contact: {
        email: "adoptions@tulsaspca.org",
        phone: "(918) 428-7722",
        address: {
          address1: "2910 Mohawk Blvd.",
          address2: null,
          city: "Tulsa",
          state: "OK",
          postcode: "74110",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644445" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ok57" },
      },
    },
    {
      id: 62644436,
      organization_id: "CA2809",
      url: "https://www.oregonhumane.org/adopt/details/279339/ ",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "American Pit Bull",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "White / Brown Brindle", secondary: null, tertiary: null },
      age: "8 years and 4 months",
      gender: "Male",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: null },
      tags: ["Crate Trained", "Good with Dogs", "Good with kids"],
      name: "King",
      description:
        "Hello and thank you for your interest in this adorable puppy. Although this puppy isn\u0026amp;#39;t old enough to be adopted...",
      organization_animal_id: "FPA-A-1552",
      photos: [
        {
          full:"../client/src/assets/images/King.jpg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:09+0000",
      published_at: "2023-04-14T17:55:08+0000",
      distance: null,
      contact: {
        email: "adoptions@fostersandpaws.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Sacramento",
          state: "CA",
          postcode: "95825",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644436" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ca2809" },
      },
    },
    {
      id: 62644437,
      organization_id: "CA2809",
      url: "https://www.oregonhumane.org/adopt/details/281665/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Retriever, Mix",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "White / Tan", secondary: null, tertiary: null },
      age: "1 years and 3 months",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: null },
      tags: ["Crate Trained", "Good with Dogs", "Good with kids"],
      name: "Daniel Buttercup Jr.",
      description:
        "Hello and thank you for your interest in this adorable puppy. Although this puppy isn\u0026amp;#39;t old enough to be adopted...",
      organization_animal_id: "FPA-A-1548",
      photos: [
        {
          full: "../client/src/assets/images/DanielButterCupJr.jpeg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:09+0000",
      published_at: "2023-04-14T17:55:08+0000",
      distance: null,
      contact: {
        email: "adoptions@fostersandpaws.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Sacramento",
          state: "CA",
          postcode: "95825",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644437" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ca2809" },
      },
    },
    {
      id: 62644438,
      organization_id: "CA2809",
      url: "https://www.oregonhumane.org/adopt/details/282059/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "American Pit Bull",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "White / Brown", secondary: null, tertiary: null },
      age: "1 years and 3 months",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: null },
      tags: ["Crate Trained", "Good with Dogs", "Good with kids"],
      name: "Rueben",
      description:
        "Hello and thank you for your interest in this adorable puppy. Although this puppy isn\u0026amp;#39;t old enough to be adopted...",
      organization_animal_id: "FPA-A-1553",
      photos: [
        {
          full:"../client/src/assets/images/Rueben.jpg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:09+0000",
      published_at: "2023-04-14T17:55:08+0000",
      distance: null,
      contact: {
        email: "adoptions@fostersandpaws.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Sacramento",
          state: "CA",
          postcode: "95825",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644438" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ca2809" },
      },
    },
    {
      id: 62644439,
      organization_id: "CA2809",
      url: "https://www.oregonhumane.org/adopt/details/284511/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Siberian Husky",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "Tan / Black", secondary: null, tertiary: null },
      age: "4 months",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: null },
      tags: ["Crate Trained", "Good with Dogs", "Good with kids"],
      name: "Dante",
      description:
        "Hello and thank you for your interest in this adorable puppy. Although this puppy isn\u0026amp;#39;t old enough to be adopted...",
      organization_animal_id: "FPA-A-1551",
      photos: [
        {
          full: "client/src/assets/images/Dante.jpg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:09+0000",
      published_at: "2023-04-14T17:55:08+0000",
      distance: null,
      contact: {
        email: "adoptions@fostersandpaws.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Sacramento",
          state: "CA",
          postcode: "95825",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644439" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ca2809" },
      },
    },
    {
      id: 62644440,
      organization_id: "CA2809",
      url: "https://www.oregonhumane.org/adopt/details/284279/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Rottweiler",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "Red / Black", secondary: null, tertiary: null },
      age: "1 years and 6 months",
      gender: "Male",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: null },
      tags: ["Crate Trained", "Good with Dogs", "Good with kids"],
      name: "Sir Maximus Prime",
      description:
        "Hello and thank you for your interest in this adorable puppy. Although this puppy isn\u0026amp;#39;t old enough to be adopted...",
      organization_animal_id: "FPA-A-1550",
      photos: [
        {
          full: "../client/src/assets/images/SirMaximusPrime.jpeg",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:09+0000",
      published_at: "2023-04-14T17:55:08+0000",
      distance: null,
      contact: {
        email: "adoptions@fostersandpaws.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Sacramento",
          state: "CA",
          postcode: "95825",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644440" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ca2809" },
      },
    },
    {
      id: 62644441,
      organization_id: "CA2809",
      url: "https://www.oregonhumane.org/adopt/details/283871/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "American Pit Bull",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "White / Tan", secondary: null, tertiary: null },
      age: "2 years and 1 months",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: null },
      tags: ["Crate Trained", "Good with Dogs", "Good with kids"],
      name: "Filo",
      description:
        "Hello and thank you for your interest in this adorable puppy. Although this puppy isn\u0026amp;#39;t old enough to be adopted...",
      organization_animal_id: "FPA-A-1549",
      photos: [
        {
          full: "../client/src/assets/images/Filo.png",
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:55:09+0000",
      published_at: "2023-04-14T17:55:08+0000",
      distance: null,
      contact: {
        email: "adoptions@fostersandpaws.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Sacramento",
          state: "CA",
          postcode: "95825",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644441" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/ca2809" },
      },
    },
    {
      id: 62644434,
      organization_id: "SC572",
      url: "https://www.oregonhumane.org/adopt/details/283468/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Labrador, Mix",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: "White / Black",
        secondary: null,
        tertiary: null,
      },
      age: "5 years and 2 months",
      gender: "Male",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: null },
      tags: [],
      name: "Artemis",
      description:
        "Marvel is spaye, up-to-date on age-appropriate vaccinations, and microchipped.\n\n**Please note: completing an \u0026quot;adoption inquiry\u0026quot; via Adopt-a-pet/Petfinder does not constitute...",
      organization_animal_id: null,
      photos: [
        {
          full: "../client/src/assets/images/Artemis.jpg",
        },
      ],
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:58+0000",
      published_at: "2023-04-14T17:54:57+0000",
      distance: null,
      contact: {
        email: "info@hfgdr.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Berkeley Heights",
          state: "NJ",
          postcode: "07922",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644434" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/sc572" },
      },
    },
    {
      id: 62644433,
      organization_id: "WI04",
      url: "https://www.oregonhumane.org/adopt/details/285405/",
      type: "Dog",
      species: "Dog",
      breeds: { primary: "Rottweiler", secondary: null, mixed: false, unknown: false },
      colors: { primary: "Tan / Black", secondary: null, tertiary: null },
      age: "8 months",
      gender: "Male",
      size: "Medium",
      coat: "null",
      attributes: {
        spayed_neutered: false,
        house_trained: true,
        declawed: null,
        special_needs: false,
        shots_current: false,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: ["Friendly", "Affectionate", "Gentle"],
      name: "Dutch",
      description:
        "Meet Alina, our lovely female rat, a young adult who is ready to find her forever home! She is a...",
      organization_animal_id: null,
      photos: [
        {
          full: "../client/src/assets/images/Dutch.jpg"
        },
      ],
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:52+0000",
      published_at: "2023-04-14T17:54:51+0000",
      distance: null,
      contact: {
        email: null,
        phone: "(608) 781-4014",
        address: {
          address1: "911 Critter Court",
          address2: null,
          city: "Onalaska",
          state: "WI",
          postcode: "54650",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644433" },
        type: { href: "/v2/types/small-furry" },
        organization: { href: "/v2/organizations/wi04" },
      },
    },
    {
      id: 62644432,
      organization_id: "AL138",
      url: "https://www.oregonhumane.org/adopt/details/285438/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Shepherd",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "Brown / Black", secondary: null, tertiary: null },
      age: "5 months",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: false,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Peppermint",
      description:
        "Budweiser is a handsome black lab mix. He was turned in by no fault of his own to our shelter....",
      organization_animal_id: "19183502-2023-26835K",
      photos: [{
        full:"../client/src/assets/images/Peppermint.jpg"
      }],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:42+0000",
      published_at: "2023-04-14T17:54:41+0000",
      distance: null,
      contact: {
        email: "thedogpound7889@yahoo.com",
        phone: "(256) 771-7889",
        address: {
          address1: "1701 Hwy 72 East",
          address2: null,
          city: "Athens",
          state: "AL",
          postcode: "35611",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644432" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/al138" },
      },
    },
    {
      id: 62644429,
      organization_id: "NY12",
      url: "https://www.oregonhumane.org/adopt/details/283898/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Shepherd",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "White / Seal", secondary: null, tertiary: null },
      age: "9 months",
      gender: "Female",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Bailey",
      description:
        "What my friends at ACC say about me:\nI can go home today!\nI am finding the shelter a little...",
      organization_animal_id: "165841",
      photos: [
        {
        full: "../client/src/assets/images/Bailey.jpg"
        }
     ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:40+0000",
      published_at: "2023-04-14T17:54:39+0000",
      distance: null,
      contact: {
        email: "adopt@nycacc.org",
        phone: "(212) 788-4000",
        address: {
          address1: "326 East 110 Street",
          address2: null,
          city: "New York",
          state: "NY",
          postcode: "10029",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644429" },
        type: { href: "/v2/types/cat" },
        organization: { href: "/v2/organizations/ny12" },
      },
    },
    {
      id: 62644430,
      organization_id: "NY12",
      url: "https://www.oregonhumane.org/adopt/details/285419/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "German Shepherd, Labrador",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "White / Brindle", secondary: null, tertiary: null },
      age: "8 years",
      gender: "Male",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Gaston",
      description:
        "What my friends at ACC say about me:\nMy history is a mystery and my friends here do not know...",
      organization_animal_id: "168736",
      photos: [
        {
          full: "../client/src/assets/images/Gaston.jpg"
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:40+0000",
      published_at: "2023-04-14T17:54:39+0000",
      distance: null,
      contact: {
        email: "adopt@nycacc.org",
        phone: "(212) 788-4000",
        address: {
          address1: "326 East 110 Street",
          address2: null,
          city: "New York",
          state: "NY",
          postcode: "10029",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644430" },
        type: { href: "/v2/types/cat" },
        organization: { href: "/v2/organizations/ny12" },
      },
    },
    {
      id: 62644431,
      organization_id: "NY12",
      url: "https://www.oregonhumane.org/adopt/details/285437/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Shepherd",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "Brown / Black", secondary: null, tertiary: null },
      age: "1 years",
      gender: "Female",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Mrs. Brisby",
      description:
        "What my friends at ACC say about me:\nMy history is a mystery and my friends here do not know...",
      organization_animal_id: "168755",
      photos: [
        {
          full: "../client/src/assets/images/MrsBrisby.jpg"
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:40+0000",
      published_at: "2023-04-14T17:54:39+0000",
      distance: null,
      contact: {
        email: "adopt@nycacc.org",
        phone: "(212) 788-4000",
        address: {
          address1: "326 East 110 Street",
          address2: null,
          city: "New York",
          state: "NY",
          postcode: "10029",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644431" },
        type: { href: "/v2/types/cat" },
        organization: { href: "/v2/organizations/ny12" },
      },
    },
    {
      id: 62644426,
      organization_id: "MS134",
      url: "https://www.petfinder.com/cat/mabel-62644426/ms/west-point/west-point-clay-county-animal-shelter-ms134/?referrer_id=53a34e66-34a5-403b-8f2a-f56735e9b210",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Terrier",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: { primary: "Tri Color", secondary: null, tertiary: null },
      age: "2 years",
      gender: "Male",
      size: "Small",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: null, dogs: null, cats: null },
      tags: [],
      name: "Scrat The Squirrel",
      description: null,
      organization_animal_id: null,
      photos: [
        {
          full: "../client/src/assets/images/ScratTheSquirrel.jpg"
        }
      ],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:27+0000",
      published_at: "2023-04-14T17:54:26+0000",
      distance: null,
      contact: {
        email: "wpccanimalshelter@gmail.com",
        phone: "(662) 524-4430",
        address: {
          address1: "5122 Old Tibbee Road",
          address2: null,
          city: "West Point",
          state: "MS",
          postcode: "39773",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644426" },
        type: { href: "/v2/types/cat" },
        organization: { href: "/v2/organizations/ms134" },
      },
    },
    {
      id: 62644425,
      organization_id: "TX2603",
      url: "https://www.oregonhumane.org/adopt/details/281973/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "German Shepherd, Siberian Husky",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: { primary: "White / Tan", secondary: null, tertiary: null },
      age: "2 years and 3 months",
      gender: "Male",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: true,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: true },
      tags: [
        "Friendly",
        "Affectionate",
        "Loyal",
        "Gentle",
        "Quiet",
        "Couch potato",
      ],
      name: "Grandpa",
      description:
        "Meet Samantha, the six-pound Chihuahua with a heart of gold! Samantha is a gentle and affectionate little girl who loves...",
      organization_animal_id: null,
      photos: [
        {
          full: "../client/src/assets/images/Grandpa.jpg",
        },
      ],
      primary_photo_cropped: {
      },
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:26+0000",
      published_at: "2023-04-14T17:54:25+0000",
      distance: null,
      contact: {
        email: "specialtreasuresanimalrescue@gmail.com",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Fort Worth",
          state: "TX",
          postcode: "76132",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62644425" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/tx2603" },
      },
    },
    {
      id: 62533328,
      organization_id: "SC574",
      url: "https://www.oregonhumane.org/adopt/details/280738/",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Chihuahua, Terrier",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: "Tan",
        secondary: null,
        tertiary: null,
      },
      age: "3 years and 4 months",
      gender: "Male",
      size: "Small",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: true,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: { children: true, dogs: true, cats: true },
      tags: [
        "Friendly",
        "Affectionate",
        "Quiet",
        "Dignified",
        "Couch potato",
        "Gentle",
        "Loyal",
        "Loves kisses",
      ],
      name: "Marlon Brando",
      description:
        "Sarge is an apx 8 y/o gentle giant who did not get the greatest start in life, having been abused...",
      organization_animal_id: null,
      photos: [
        {
          full: "../client/src/assets/images/MarlonBrando.jpeg",
        },
      ],
      primary_photo_cropped: {
      },
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-14T17:54:21+0000",
      published_at: "2023-04-14T17:54:20+0000",
      distance: null,
      contact: {
        email: "save@arcadiarescue.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Wendell",
          state: "NC",
          postcode: "27591",
          country: "US",
        },
      },
      _links: {
        self: { href: "/v2/animals/62533328" },
        type: { href: "/v2/types/dog" },
        organization: { href: "/v2/organizations/sc574" },
      },
    },
  ],
  pagination: {
    count_per_page: 20,
    total_count: 254757,
    current_page: 1,
    total_pages: 12738,
    _links: { next: { href: "/v2/animals?page=2" } },
  },
};
